name: toward_purpose
description: The Toward Purpose app
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.0.14
  build_runner: ^2.1.4
  hive_generator: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  # add any additional Flutter-specific settings here
